Get response from servlet
googleinterns/step64-2020 pull request #2
Opened 2020-06-24 22:42 UTC by jonaner

2020-06-24 23:02 UTC, jbiral requested changes
The JS formatting check is broken, could you run `make pretty`? Thanks!

2020-06-24 23:02 UTC, jbiral commented on src/main/webapp/script.js
>  // TODO: Add functions below
You can remove this line now

2020-06-24 23:02 UTC, jbiral commented on src/main/webapp/style.css
> -  margin-right: auto;
These help centering the page, shouldn't we keep them?

2020-06-24 23:30 UTC, ginellegaisano approved these changes

2020-06-24 23:41 UTC, jbiral approved these changes

2020-06-25 07:24 UTC, shivanighanta approved these changes

2020-06-26 22:06 UTC, merged