Added sentiment, syntax and entity analysis methods
googleinterns/step64-2020 pull request #3
Opened 2020-06-29 21:11 UTC by shivanighanta

2020-06-30 15:46 UTC, jbiral requested changes
Overall, this is looking good!

A couple things I'd like to ask / point out:
1. I'd like to see how `doGet` is instantiating and calling the `Analyze` class to have more clarity on its intended use. It's fine to call it with dummy data for now and include it in the PR. This way, Bless can update the dummy data later to real data once it's ready.
1. Do we need to close the Service after each request, or can we re-use it multiple times before closing it? If it's the latter, I would suggest to keep the service open for the duration of the `doGet` method call, so we don't need to re-create the service if we have multiple posts to process.
1. Try to sub out the service, as suggested in the pod chat, so tests can be kept while not calling the real endpoint.
1. The lint / formatting checks are broken, so make sure to address them as otherwise the PR cannot be merged.

2020-06-30 15:46 UTC, jbir789 commented on src/main/java/com/google/sps/language/Analyze.java
> +    LanguageServiceClient languageService = LanguageServiceClient.create();
Could you use a try with resources here as well?

2020-06-30 15:46 UTC, jbir789 commented on src/main/java/com/google/sps/language/Analyze.java
> +  public static void analyzeEntitiesText(String text) throws Exception {
I would recommend not making these static, so you can share class variables if needed.

2020-06-30 20:37 UTC, ginellegaisano reviewed
I left a few comments - generally looks good, though would recommend going through and refactoring so that methods with duplication can share code. I noticed that the difference between a lot of these pairs of functions is that one sets a gcsUri and the other sets text. The rest can go into a helper. (ie. analyzeEntitiesFile and analyzeEntitiesText can have a helper called analyzeEntities(Document doc)).

2020-06-30 20:37 UTC, ginellegaisano commented on src/main/java/com/google/sps/language/Analyze.java
> +    // float score = Math.round(sentiment.getScore() * 100.0) / 100.0;
Nit: delete commented line.

2020-06-30 20:37 UTC, ginellegaisano commented on src/main/java/com/google/sps/language/Analyze.java
> +        Document.newBuilder().setContent(message).setType(Document.Type.PLAIN_TEXT).build();
If this, line 63, line 125 need to be kept in-sync, it might be worth creating a helper method to share between.

2020-06-30 20:37 UTC, ginellegaisano commented on src/main/java/com/google/sps/language/Analyze.java
> +      for (Entity entity : response.getEntitiesList()) {
If you plan on keeping this, extract code into separate method to use on line 105 as well.

2020-06-30 20:37 UTC, ginellegaisano commented on src/main/java/com/google/sps/language/Analyze.java
> +      if (sentiment == null) {
Same here - extract into helper to share with #analyzeSentimentFile

2020-07-06 18:52 UTC, shivanighanta commented
> Overall, this is looking good!
> 
> A couple things I'd like to ask / point out:
> 
> 1. I'd like to see how `doGet` is instantiating and calling the `Analyze` class to have more clarity on its intended use. It's fine to call it with dummy data for now and include it in the PR. This way, Bless can update the dummy data later to real data once it's ready.
> 2. Do we need to close the Service after each request, or can we re-use it multiple times before closing it? If it's the latter, I would suggest to keep the service open for the duration of the `doGet` method call, so we don't need to re-create the service if we have multiple posts to process.
> 3. Try to sub out the service, as suggested in the pod chat, so tests can be kept while not calling the real endpoint.
> 4. The lint / formatting checks are broken, so make sure to address them as otherwise the PR cannot be merged.

Since the main functionality of the methods is to call the language API, I'm not sure if subbing out the service would make sense in this situation.

2020-07-06 18:59 UTC, jbir789 commented
Currently, yes, but you could imagine it will do more processing of the sentiment score later down the road, in which case it'll be helpful to be able to stub the service.

The thing is we can't write a test as long as we're calling the real API. And that may be fine for this CL, but we will need to stub something at some point (either this class, or the service and suggested)

2020-07-06 20:25 UTC, shivanighanta commented
Ok, that makes sense. I'll do that in the next PR when I process the sentiment score further.

2020-07-06 20:42 UTC, jbiral approved these changes

2020-07-06 20:42 UTC, jbir789 commented on src/main/java/com/google/sps/servlets/DataServlet.java
> +  private Analyze analyze = new Analyze();
nit: add an empty line before and after this variable (and let's make it final too).

2020-07-06 20:42 UTC, jbir789 commented on src/main/java/com/google/sps/servlets/DataServlet.java
>      response.getWriter().println("<h1>Hello world!</h1>");
Could you update the response with a sentiment score, for example? I know it won't be final, but this way we can see a reflection of the sentiment API into the response

2020-07-06 20:42 UTC, jbir789 commented on src/test/java/com/google/sps/AnalyzeTest.java
> +@Ignore
Please add a comment to explain why the test is ignored:

```java
@Ignore // Comment here
```

2020-07-06 21:30 UTC, ginellegaisano commented on src/main/java/com/google/sps/language/Analyze.java
> +  public void analyzeEntitiesText(String text) throws Exception {
Should these return Entity?

2020-07-06 21:30 UTC, ginellegaisano commented on src/main/java/com/google/sps/language/Analyze.java
> +  public void analyzeEntities(Document doc, LanguageServiceClient language) throws Exception {
I think you'll probably want this one to be private, so that callers need to use analyzeEntitiesFile or analyzeEntitiesText instead. Also with the rest of the helpers.

2020-07-06 21:30 UTC, ginellegaisano commented on src/main/java/com/google/sps/language/Analyze.java
> +  public void classifyText(String text) throws Exception {
Should this return ClassificationCategory? Same below.

2020-07-06 21:30 UTC, ginellegaisano commented on src/main/java/com/google/sps/language/Analyze.java
> +  public void entitySentimentText(String text) throws Exception {
Should these return Entity? Same below.

2020-07-06 21:30 UTC, ginellegaisano commented on src/main/java/com/google/sps/servlets/DataServlet.java
> +package com.google.sps;
OOC, why did this package name change?

2020-07-06 22:16 UTC, shivanighanta commented on src/main/java/com/google/sps/servlets/DataServlet.java
> +package com.google.sps;
I wasn't able to access the methods in the Analyze class unless they were in the same package.

2020-07-08 13:28 UTC, jonaner approved these changes
In addition to prior reviews, I think this looks good.

2020-07-08 15:34 UTC, BlessP approved these changes

2020-07-08 16:32 UTC, ginellegaisano approved these changes

2020-07-13 04:55 UTC, shivanighanta commented on src/main/java/com/google/sps/language/Analyze.java
> +  public void entitySentimentText(String text) throws Exception {
I wanted to print out all the enitity attributes for this PR to check the natural languge API is returning all the right things. After checking how the methods interact with the youtube API I'll change the return values of the methods to what makes most sense.

2020-07-13 16:03 UTC, merged